# Generated by Django 4.1 on 2024-07-07 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food_nutrition_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Food",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("fdcId", models.CharField(max_length=100)),
                ("desc", models.CharField(max_length=100)),
                ("brandName", models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name="post",
            name="author",
        ),
        migrations.DeleteModel(
            name="Author",
        ),
        migrations.DeleteModel(
            name="Post",
        ),
    ]
